// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://onanrpmrgdfjsrtwckxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9uYW5ycG1yZ2RmanNydHdja3hpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgzMjUyMjIsImV4cCI6MjA4MzkwMTIyMn0.OcfKhEWiA5w5uG_eYK58SiDVtkKfTzxrnNOBMJbgHVU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);